#jwt
jwt:
  authorization: Authorization
  # token-prefix
  token-prefix: Bearer
  # secret
  base64-secret: 1a2b3c
  expiration-remember: 604800 # 7天，s为单位 60 * 60 * 24 * 7
  expiration-time: 86400 # 1天

#spring
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/track-square
    username: root
    password: admin
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
